

export const AUTH_COPY = {
	loginSkip: 'Skip',
	loginRememberMe: 'Remember my login for faster Sign-in',
	loginContinue: 'Continue',
	phoneValidationMessage: 'Enter a valid 10-digit mobile number',
	loginTitle: 'A better way to experience food.',
	loginDivider: 'Log in or sign up',
	loginFooterPrefix: 'By continuing , you agree to our',
	termsOfService: 'Terms of service',
	privacyPolicy: 'Privacy Policy',
	contentPolicy: 'Content Policy',
	socialDivider: 'Or',
	otpTitle: 'OTP Verification',
	otpSubtitlePrefix: 'We have sent a verification code to',
	otpResendPrefix: "Didn't receive the code? ",
	otpResendAction: 'Resend OTP',
	otpSubmit: 'Submit',
	countryCode: '+91',
	phonePlaceholder: 'Enter Phone Number',
	brandTitle: 'FreshBhoj',
} as const;

export const AUTH_VALUES = {
	otpDigits: 6,
	phoneMaxLength: 10,
	phoneDigitsRegex: /^\d{10}$/,
	phoneNonDigitRegex: /\D/g,
	loginHeaderTopIos: 70,
	loginHeaderTopAndroid: 50,
	loginContinueGradientLocations: [0.09, 0.77, 1] as [number, number, number],
	otpHeaderGradientLocations: [0, 1] as [number, number],
	loginTopSectionHeightRatio: 0.4,
	loginPlateImageWidthRatio: 1.15,
	loginPlateImageTopOffset: -100,
	loginBrandTitleTopOffset: -120,
	otpImageWidthRatio: 0.8,
	otpImageHeightRatio: 0.4,
	mockOtp: '123456',
} as const;
